# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/CodeTest
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/CodeTest
    - name: Test
      working-directory: src/CodeTest.UnitTest
      run: dotnet test CodeTest.UnitTest.csproj  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura
    - name: Install reportgenerator tool
      working-directory: src/CodeTest.UnitTest
      run: dotnet tool install dotnet-reportgenerator-globaltool
    - name: Generate code coverage Markdown report
      working-directory: src/CodeTest.UnitTest
      run: dotnet reportgenerator -reports:**/coverage.cobertura.xml -targetdir:./coverage -reporttypes:MarkdownSummary
    - name: Create check run with code coverage Markdown report
      uses: LouisBrunner/checks-action@v1.2.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Code coverage
        conclusion: ${{ job.status }}
        output: '{"summary":"Code coverage"}'
        output_text_description_file: ${{ github.workspace }}/src/CodeTest.UnitTest/coverage/Summary.md
